export const FETCH_SIGNIN = 'FETCH_SIGNIN';
export const FETCH_SIGNIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS';
export const FETCH_SIGNIN_FAILURE = 'FETCH_SIGNIN_FAILURE';

export const LOG_OUT = 'LOG_OUT';

export const FETCH_RECOVERY = 'FETCH_RECOVERY';
export const FETCH_RECOVERY_SUCCESS = 'FETCH_RECOVERY_SUCCESS';

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const ADD_CHILD = 'ADD_CHILD';
export const UPDATE_CHILD = 'UPDATE_CHILD';
export const DELETE_CHILD = 'DELETE_CHILD';

export const ADD_PHONE = 'ADD_PHONE';
export const UPDATE_PHONE = 'UPDATE_PHONE';
export const DELETE_PHONE = 'DELETE_PHONE';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const UPLOAD_FILE = 'UPLOAD_FILE';

export const FETCH_POSITIONS_SUCCESS = 'FETCH_POSITIONS_SUCCESS';